### ISSUE TITLE
Multiple ContentEditable components, lost focus

### ISSUE THREAD

**Issue by Evgenyx82** [lovasoa/react-contenteditable#100]
Hi, there.
Seems i have found once more bug.

Preface: I have been layout big table (about 66*8 cells, for one table, and i have same 31 tables in one page), for cells i have been used your library. 

I have the (https://codesandbox.io/s/9yl7py535p) code snippet for demonstration my problem...

when the url open, try to type in upper div, and as we can see, second div become focused...

i want type something into cell, but after validations and some aggregations update some cell to show some info.

**Comment by lovasoa** [comment]
This must have been introduced in 0b313c4fc6d06660e12009d7601cd98e12791b0b
