### ISSUE TITLE
Require not working as expected on NodeJS

### ISSUE THREAD

**Issue by sebasgarcep** [lovasoa/react-contenteditable#12]
Not sure if you can call this a bug, but the `export default` statement exports not the class but an object that places the module at the `default` key. This is intended by the transpiler as https://github.com/esnext/es6-module-transpiler/issues/85 suggests and they provide solutions for importing on CommonJS systems. Should we change the example on the Readme so that it is valid in every case, or should we export using module.exports to make the require syntax valid in Node (I don't know if this may have other repercussions)?

**Comment by lovasoa** [comment]
Thank you very much.

**Comment by sebasgarcep** [comment]
Not sure this solves the issue... Wont' recompiling the library erase the line on the `lib/react-contenteditable.js` file?

**Comment by lovasoa** [comment]
The line wasn't added manually, but by this babel plugin: https://github.com/lovasoa/react-contenteditable/blob/master/package.json#L34

**Comment by sebasgarcep** [comment]
Oops sorry! Thanks for the fix then.
