### ISSUE TITLE
Repeating a key quickly causes text insertion without an emitted event.

### ISSUE THREAD

**Issue by SethTompkins** [lovasoa/react-contenteditable#13]
I have been attempting to create a way to limit the amount of characters that are input into a ContentEditable component. The only issue is that if a user types quickly enough, characters will be inserted into the DOM without a matching `onChange` event being emitted from the component.

You can test this by simply putting a `console.log` inside the `onChange` callback and counting the amount of key strokes and the amount of log messages on your console.

**Comment by SethTompkins** [comment]
Changing this line https://github.com/lovasoa/react-contenteditable/blob/38726a334ed62c69570750ca23377f85e87195c7/src/react-contenteditable.js#L36

to `if (this.props.onChange) {` fixed this problem entirely. Looks like `this.lastHtml` or `this.htmlEl.innterHTML` are not accurate for contentEditable regions.

**Comment by lovasoa** [comment]
Does this still occur after the last merged PR ?

**Comment by lovasoa** [comment]
I am closing this as I cannot replicate the issue. Feel free to reopen if you manage to reproduce the issue.
