### ISSUE TITLE
Is there support for onKeypress?

### ISSUE THREAD

**Issue by snstarosciak** [lovasoa/react-contenteditable#131]
This is a really nice and simple implementation of `contentEditable` in React, however, for utilizing it for a chat, there's no ability to handle a keypress event where one can check for keyCode detection. Is there any way for this to be done? Thanks!

**Comment by lovasoa** [comment]
standard javascript event handlers work just fine , including onKeyPress.
Please read the react documentation about event handling.
https://codesandbox.io/s/lx813nwkn7

**Comment by lovasoa** [comment]
fixed by #136
