### ISSUE TITLE
Allow refs to be used

### ISSUE THREAD

**Issue by davidbarton** [lovasoa/react-contenteditable#15]
Refs are now used to work with inner html, please allow refs to be specified and executed with html magic

**Comment by Treora** [comment]
Could you (or anyone) explain the issue, for the muggles among us that are unaware of html magic? :)

**Comment by davidbarton** [comment]
Hi, sorry for vague description. Issue is I am not able to provide my own `ref` props since react-contenteditable does not expect them and rewrites `ref` with its own function (`ref: (e) => this.htmlEl = e`). Solution is to wrap injected `ref` with react-contenteditable and apply both of them.

**Comment by Treora** [comment]
Ok. I do not know enough about `ref`s to deal with this issue. I somehow
assumed they are supposed to be used only within a component, and not to
be passed around between components.

**Comment by wchaering** [comment]
Found myself wanting this as well and added support for it in PR #55

**Comment by naoufal1** [comment]
+1

**Comment by naoufal1** [comment]
You can use this syntax to access the node used as editable
![image](https://user-images.githubusercontent.com/11160251/28160453-1e9e5db4-67b8-11e7-8568-a5ef2023ddd9.png)

**Comment by lovasoa** [comment]
You can get a ref to the underlying DOM element by accessing the `htmlEl` property of a reference to your `ContentEditable` component. See this example: https://codesandbox.io/s/mq53w1jo08
