### ISSUE TITLE
ContentEditable is becoming focused when parent container is clicked

### ISSUE THREAD

**Issue by dcporter44** [lovasoa/react-contenteditable#156]
For some reason that I cannot figure out, when I click on the parent of the contenteditable it is causing the field to be focused. I'm wrapping it in a standard div with Bootstrap class "col-12". It's anonoying because when I want to blur, I have to click out of the parent as well. I remains focused when clicking outside of the ContentEditable but still inside the parent. Any ideas?

**Comment by lovasoa** [comment]
Hi ! By reading what you wrote, I'm not sure this is a problem with this library. Can you provide a reproducible example ? On [codesanbox](https://codesandbox.io/s/4rlw34mnk7) for instance.

**Comment by dcporter44** [comment]
Yep, reproduced here: https://codesandbox.io/s/n5969l74l

All I had to do was use `tagname="span"` and now its reproducible. Click in the middle of the ContentEditable, then click out of it.

**Comment by lovasoa** [comment]
I'm sorry, but I don't see any difference between the behavior [in react-contenteditable](https://codesandbox.io/s/kkwn0wl537) and [without it](https://codesandbox.io/s/j1n5vyjn9w).
I think what you are talking about is a browser behavior, not a bug in react-contenteditable. Feel free to re-open or comment if I'm mistaken.

**Comment by dcporter44** [comment]
Ah very interesting. Turns out that anytime you use a span with contenteditable, the contenteditable field will become focused upon click of the parent. 

In Safari, every time you click the parent container, it becomes focus. In Chrome, _sometimes_ it becomes focused. Really strange behavior. 

In fact, even just wrapping a contenteditable in a `span` will cause this functionality. Even if the contenteditable itself is a div.

This is a bug(?) with contenteditable as a whole, not just this library. However, I would highly recommend you mention this in your docs just to avoid future raised issues and to help future coders.

**Comment by Hitscotty** [comment]
yea, I think this is a bug, for me when ever I triple click, it focus on first contenteditable heres my issue: https://codesandbox.io/s/vqvolvoln5
