### ISSUE TITLE
What kind of user edit makes it not update? Source code comment

### ISSUE THREAD

**Issue by cbdeveloper** [lovasoa/react-contenteditable#159]
`// We need not rerender if the change of props simply reflects the user's edits.`

What does this comment mean in the source? It seems to me that when a user edits it always fire an `onInput()` and thus and `emitChange()` so it alters the `html` and it always updates, doesn't it? When does it not update? What kind of edit would that be? Thanks!

**Comment by lovasoa** [comment]
every time we update the html, the caret jumps to the end of the editable component. So while the user is typing, we have to avoid setting innerHTML as much as possible.

**Comment by lovasoa** [comment]
Is that clearer?

**Comment by cbdeveloper** [comment]
But on every char that the user adds you get a new `onInput()`, isn't it? And on every new `onInput()` you call `emitChange()`. Wound't this update html on every key stroke? How do you decide when to update and when to avoid? I didn't get that. This package helped me a lot. Thank you.

**Comment by lovasoa** [comment]
No, emitChange does not update the HTML. I encourage you to read the react documentation to learn about the component lifecycle and shouldComponentUpdate: 

https://reactjs.org/docs/react-component.html
