### ISSUE TITLE
I need one button to wrap selected text in "UL/LI"?

### ISSUE THREAD

**Issue by pravingkd6** [lovasoa/react-contenteditable#163]
Hello,
I need one button to wrap selected text in "UL/LI",
If I click to button then entire text block should convert in an ordered or unordered list, Please help?

**Comment by lovasoa** [comment]
The issues section is not really the place you should be asking for general help, so I'm closing the issue. You can ask such questions on stackoverflow, for instance.

That being said, `document.exeCommand` should be able to do what you want: https://developer.mozilla.org/en-US/docs/Web/API/Document/execCommand
