### ISSUE TITLE
On paste content from (word, libre office)document  not respect format

### ISSUE THREAD

**Issue by canotech** [lovasoa/react-contenteditable#170]
Hi, on paste  content from word document and some styling as "bold" does not visual respect, but when I render the content of editor in another component  this it show of correct form, but in the editor not visualize of correct form, that is it can would confused user, I need respect that format integrity
![Screen Shot 2019-08-08 at 5 45 58 PM](https://user-images.githubusercontent.com/33262684/62742532-86759880-ba04-11e9-93c1-312a5f037522.png)
![Screen Shot 2019-08-08 at 5 46 15 PM](https://user-images.githubusercontent.com/33262684/62742534-86759880-ba04-11e9-9780-e197ce5b356d.png)

**Comment by lovasoa** [comment]
This is not an bug in react-contenteditable, this is how contenteditable works. 

If you are trying to get help with how to use contenteditable elements, then you should do it on a specialized website such as stackoverflow.
