### ISSUE TITLE
Remove dependency over '@types/prop-types'

### ISSUE THREAD

**Issue by SebCorbin** [lovasoa/react-contenteditable#171]
Using `@types/prop-types` as hard dependency triggers annoying warnings for non typescript projects, see https://intellij-support.jetbrains.com/hc/en-us/community/posts/360003783160-React-Native-prop-types-module-Default-export-is-not-declared-in-imported-module-

Is it possible to declare it as `devDependencies`? If required use `prop-types` package for building.

**Comment by lovasoa** [comment]
Hello!
  [prop-types](https://www.npmjs.com/package/prop-types) is not specific to Typescript projects (actually it's most useful in non-typescript projects), and it would be useless in devDependencies. See https://www.npmjs.com/package/prop-types#how-to-depend-on-this-package

The problem might rather be that prop-types itself is missing from the dependencies; only `@types/prop-types` is included.

**Comment by SebCorbin** [comment]
If I understand correctly, are you saying we should move `@types/prop-types` to devDependencies and use `prop-types` in dependencies?

**Comment by lovasoa** [comment]
Since we are reexporting types from proptypes as part of the ContentEditable class, both `@types/prop-types` and `prop-types` should be in dependencies.

**Comment by lovasoa** [comment]
You can make the change, test it, and open a pull request.
