### ISSUE TITLE
Placeholder

### ISSUE THREAD

**Issue by IRYNA-MAZURA** [lovasoa/react-contenteditable#179]
In the browser IE the carriage be comes after placeholder.

https://imgur.com/a/XbOEovq

**Comment by lovasoa** [comment]
This library does not support placeholders. You must have a custom placeholder implementation, that is buggy.
If a detailed issue report is provided, I'll reopen this issue.

**Comment by YuenSC** [comment]
just want to share my implementatnion of placeholder based on the **::before**  in css.  btw I am not sure why sometimes if I first select all text by **control + a** and then delete the text, I will get "<div><br></div>" or "<br>". just tested that in chrome. 

<img width="1251" alt="Screenshot 2024-03-07 at 10 26 07 AM" src="https://github.com/lovasoa/react-contenteditable/assets/48469559/b2882d2a-c620-48c3-a50f-7742e27e865e">
