### ISSUE TITLE
How to set maxlength for this React Component?

### ISSUE THREAD

**Issue by skur42** [lovasoa/react-contenteditable#185]

**Comment by lovasoa** [comment]
This component does not have a maxlength property, but you can limit the size of the contents using event handlers.

I'm closing this, since it is not an issue. If you need help with your code, you can ask on stackoverflow or another community forum.

**Comment by hari457627** [comment]
in hooks, even i'm trying to restrict to certail length, its not working. but its working in class component. did you try with latest hooks, if you tried, kindly share the code.

**Comment by TamjidTayeb** [comment]
Hi @hari457627  Were you able to solve this issue? I'm having the same problem, can't set a character limit even with events
