### ISSUE TITLE
Unable to set autoFocus 

### ISSUE THREAD

**Issue by karthick3018** [lovasoa/react-contenteditable#188]

**Comment by lovasoa** [comment]
There is no autofocus attribute on contenteditable elements in HTML. 

Also, please give a full description for issues you report, and try to be polite. When you open an issue, you are entering in communication with a real human being. Would "unable to set autoFocus" be the first thing you would say to someone you meet for the first time ?

And issues are meant to report bugs, they are not for tech support.
