### ISSUE TITLE
How do I get/set the cursor position inside  the  editable component?

### ISSUE THREAD

**Issue by ShashankAnantharam** [lovasoa/react-contenteditable#189]
I want to get and set the position of the cursor inside  the ContentEditable component. In the onChange event, I am not able to find the position of the cursor.

```
handleChange(e){
        let htmlStr = String(e.target.value);
       let cursorPosition = ? //How  do I  get this?
        let newHtml = doSomeStuff(htmlStr);

       //How  do I  set  cursor position?
        this.setState({
            html: newHtml
        });
}
```

**Comment by lovasoa** [comment]
There is nothing specific about this library in how to get the cursor position. You do it using standard web APIs. 

https://developer.mozilla.org/en-US/docs/Web/API/Window/getSelection
