### ISSUE TITLE
Testing this component. Programmatic change doesn't fire `onChange`.

### ISSUE THREAD

**Issue by karlosos** [lovasoa/react-contenteditable#190]
Hi. First of all great component! I really appreciate it.

I have a question about testing this component. How to mimic user action in test environment? I've tried following:

```
    // The given element does not have a value setter
    fireEvent.change(sourceContent, {
      target: { value: "New content text" }
    });

    // This doesn't emit onChange Changes text content but onChange is not fired.
    fireEvent.change(sourceContent, {
      target: { textContent: "New content text" }
    });

    // This doesn't emit onChange. Changes inner html but onChange is not fired.
    fireEvent.change(sourceContent, {
      target: { innerHTML: "New content text" }
    });
```

All of the above without success. I thought that if I change `innerHTML` then function provided in `onChange` will be fired. This is sample project with this problem: https://codesandbox.io/s/ecstatic-bush-m42hw?fontsize=14&hidenavigation=1&theme=dark

**Comment by lovasoa** [comment]
You can look at our own tests in https://github.com/lovasoa/react-contenteditable/tree/master/tests 
We use puppeteer to run the tests in a real browser.
If you need more general advice on testing, you can ask a question on stackoverflow.

**Comment by karlosos** [comment]
Thanks. Your code helped me to find solution. In **react-testing-library** you should use `fireEvent.input` for testing user input. In my example I've used `fireEvent.change`. 

So, if someone want to test code that uses this component following will work:

```
    fireEvent.input(sourceContent, {
      target: { innerHTML: "New content text" }
    });

    expect(sourceContent.textContent).toBe("New content text");
    expect(targetContent.textContent).toBe("value state: New content text");
```

**Comment by sibelius** [comment]
does it work to clean some text?
