### ISSUE TITLE
Is there way to highlight entity w/o caret jumping?

### ISSUE THREAD

**Issue by f0rmat1k** [lovasoa/react-contenteditable#197]
Good day!

I have a need to highlight entities while typing. When i change value programmatically in render:
```js
value = value.replace('#tag ', '<span style="color: blue">#tag</span> ');
```
caret jumps to the end. I understand why it's happening, but maybe somebody can give advice, how to solve it.

**Comment by baptisteArnaud** [comment]
I have the exact same problem. Did you find a way to solve this? @f0rmat1k

**Comment by f0rmat1k** [comment]
Yes, but i have to move to draft-js with decorators mechanism.

**Comment by fr31b3u73r** [comment]
It is indeed a bit tricky. Check out the [this solution](https://stackoverflow.com/a/38479462). I've modified it a bit as I am using Typescript but basically it works. Just call the save method at the beginning of your onChange handler, then do the replacings and at the end call the restore method for the caret.
