### ISSUE TITLE
How do i remove <div> tags from inside the text 

### ISSUE THREAD

**Issue by Ali-hd** [lovasoa/react-contenteditable#206]
Hello I have been looking around for a solution to this but couldn't find anything clear. 

I'm trying to save the text from the <ContentEditable /> but the text has <div> tags inside it when i press enter. It gets saved to the database like that and when I use it the newl ines don't show up it only a single line with `first line <div>second line </div><div>third lin</div>`. 

I want the user to be able to press enter and have new lines just like twitter input box

**Comment by Ali-hd** [comment]
github ignored the divs and showed it correctly.. 
this is what i mean
`first line <div>second line</div><div>third line</div>`

**Comment by lovasoa** [comment]
Hello, 
  this is more of a question than an issue with this repository, so I'll close this to help with project management. Feel free to keep commenting below, though.

**Comment by lovasoa** [comment]
You may be interested to read: https://stackoverflow.com/questions/18552336/prevent-contenteditable-adding-div-on-enter-chrome/20398548

**Comment by Ali-hd** [comment]
I added 
[contenteditable=true]{display: inline-block;} 
to my css and it solved it !
