### ISSUE TITLE
possible to Select All on button click?

### ISSUE THREAD

**Issue by gfantom** [lovasoa/react-contenteditable#207]
Hi,

Just discovered this and it's great. I have a button that focuses on the component.

I'm wondering if there's a way to select all on button press? I tried `this.contentEditable.current.select();` but that doesn't seem to work.

**Comment by fstb1103** [comment]
const textInput = useRef(null);


  const changeEditableInput = () => {
    if (textInput.current) {
      textInput.current.focus()
    }
  }


<ContentEditable
        innerRef={textInput}
/>

<Button onClick={changeEditableInput}/>

**Comment by zeevl** [comment]
This works for me..

```        onFocus={e => window.getSelection()?.selectAllChildren(e.currentTarget)}
```

**Comment by lovasoa** [comment]
See https://stackoverflow.com/questions/6139107/programmatically-select-text-in-a-contenteditable-html-element
