### ISSUE TITLE
Android phone input will automatically wrap

### ISSUE THREAD

**Issue by SnailsInRunning** [lovasoa/react-contenteditable#208]
Used on Android phones, the input content will automatically wrap. On an Android phone, just enter a few characters and it will wrap

**Comment by lovasoa** [comment]
Hello, 
  There is not  enough information in this report to reproduce the issue.
  This component doesn't handle any styling, it is just a normal contenteditable div. I'll reopen this issue if someone provides a reproduction that shows the bug with react-contenteditable.
