### ISSUE TITLE
Parent prevens child elements from firing events

### ISSUE THREAD

**Issue by lauridskern** [lovasoa/react-contenteditable#217]
In the following screenshot "their" is a div with an onClick, but the event won't fire because the parent is always blocking it. How can I prevent this?
<img width="324" alt="image" src="https://user-images.githubusercontent.com/8788856/103143474-05ad5e80-4717-11eb-911d-e5120b711c4d.png">

**Comment by lovasoa** [comment]
This is not an issue with this library. If you need help for your implementation, you can ask on stackoverflow.
