### ISSUE TITLE
onKeyDown props isn't work on mobile chrome

### ISSUE THREAD

**Issue by bryantobing12** [lovasoa/react-contenteditable#220]
I try to make mention feature in my rich editor when the user press @ or inputting @ will show some modal. it is all worked perfectly on desktop chrome when the user filled input with @ but in the mobile chrome when it doesn't trigger anything.

``

**Comment by lovasoa** [comment]
This lacks context and a reproducible example.
See http://sscce.org/

I'll reopen it if it is proven to be a bug in this library.

**Comment by bryantobing12** [comment]
I use onKeydown props provided by this component. when the user press @ it will trigger a modal. in chrome desktop, it works. but when in mobile chrome it doesn't work and the modal not triggered

**Comment by lovasoa** [comment]
This sounds like a bug in your code
