### ISSUE TITLE
`contentEditable=false` elements within the ContentEditable behaves unexpectedly

### ISSUE THREAD

**Issue by vdepina** [lovasoa/react-contenteditable#231]
I'm using ContentEditable and need to have uneditable elements within the content. When I have a new line that begins with an uneditable element and I move the cursor to the start of the line then backspace from there, that line gets replaces with a `<br>` element and the original content is gone.

![2021-05-11 at 11 58 AM](https://user-images.githubusercontent.com/53443068/117847317-3b7b5b80-b250-11eb-893f-227e3431ef14.png)
![2021-05-11 at 11 58 AM](https://user-images.githubusercontent.com/53443068/117847329-3d451f00-b250-11eb-807f-817e9936acdb.png)

**Comment by lovasoa** [comment]
Hello,
  "behaves unexpectedly" is not a valid bug report.
  
Please
 - make sure that the behavior you are seeing is a bug in this library and not the normal behavior of contentEditable in whatever browser you are using. Notably, some browsers insert <br> elements in contenteditable elements. This is not a bug.
 - if what you are seeing is really a bug in this library, provide a minimal reproducible example, not a code screenshot.
