### ISSUE TITLE
save and restore selection

### ISSUE THREAD

**Issue by PlopTheReal** [lovasoa/react-contenteditable#232]
Basically the idea is to create an hyperlink on the selected text with a form to give the ability to open/not open in new window and provide the href.
As we loose the selection by focusing other elements, how do you restore the original selection?
It seems the following isn't working: https://gist.github.com/dantaex/543e721be845c18d2f92652c0ebe06aa

**Comment by PlopTheReal** [comment]
I've found that it seems to not work when the component get rerendered by react, llike it's loosing track of the selection when rerendering. 
It may be more a general react question... Any idea of the reasons for such behavior?

**Comment by lovasoa** [comment]
Yes, when rerendering it recreates the dom elements, and thus loses the state associated to them, including the selection and caret position. If you need to handle selections you will have to use the web APIs directly
