### ISSUE TITLE
Obejct given to 'style' property gets changed to not-writable.

### ISSUE THREAD

**Issue by kimmin920** [lovasoa/react-contenteditable#233]
Hello, 

While I'm enjoying your module, have a question about 'style' property.

Please, see this example below. try to edit the texts, and check the console.
https://codesandbox.io/s/rough-snowflake-pdsq2

After passed an object to the 'style' property of 'Contenteditable' component, 
a 'writable' property of the object gets changed to FALSE.

I figured out it works fine if I passed destructured object, like below.
It doesn't get changed it's writable to false.

```jsx
<ContentEditable
    html={texts}
    style={{ ...styles }}
    onChange={(e) => onChange(e, index, 'texts')}
    disabled={!isEditable}
/>
```

but I still wonder if it's intended or not, and why is it happening.

Thank you!

**Comment by lovasoa** [comment]
This is how react works, this is not related to this library.

Try for instance

```jsx
import React from "react";
import ReactDOM from "react-dom";

class MyComponent extends React.Component {
  constructor() {
    super();
    this.state = { html: new Date().toString() };
  }

  style = {
    color: "red"
  };

  render = () => {
    console.log(Object.getOwnPropertyDescriptor(this.style, "color"));

    return (
      <div
        style={this.style}
        onClick={() => {
          this.setState({ html: new Date() });
        }}
      >
        {this.state.html.toString()}
      </div>
    );
  };
}

const rootElement = document.getElementById("root");
ReactDOM.render(<MyComponent />, rootElement);
```

**Comment by kimmin920** [comment]
oh sorry, I never knew that before. and Thank you for quick response.
