### ISSUE TITLE
When using Firefox and pressing enter, a <br> tag is added to the saved html

### ISSUE THREAD

**Issue by kevinarthur2077** [lovasoa/react-contenteditable#248]
This tag is then rendered as part of the name elsewhere in the app but it doesn't show up in the contenteditable box so there isn't a way to delete it short of going into the DB and removing from there. Is there a way to prevent that behavior from happening in Firefox? Doesn't happen in Chrome. Firefox version is 93.0, so it's a modern version.

Also, is there a way to render the `<br>` tag as text in the contenteditable box so that I could delete it?

**Comment by lovasoa** [comment]
This is how contenteditable elements work in Firefox, this is not an issue with this library.
