### ISSUE TITLE
Custom components in html?

### ISSUE THREAD

**Issue by georgevcr2** [lovasoa/react-contenteditable#249]
I am trying to pass a custom component through the 'html' prop; however when I do it makes the component lowercase and does not treat them as expected.

`<ContentEditable
                key="editor1"
                html="<MyCustomComponent />"
                spellCheck="false"
                disabled={false} 
                onChange={handleChange}
              />`

Is this a limitation of the package?

**Comment by lovasoa** [comment]
Yes, the html attribute is not managed by react. It expects raw HTML, it doesn't know about your components (except if you use custom elements: https://developer.mozilla.org/en-US/docs/Web/Web_Components/Using_custom_elements).
