### ISSUE TITLE
Add flag to paste plain text.

### ISSUE THREAD

**Issue by mewben** [lovasoa/react-contenteditable#31]
This seems to work: http://jsfiddle.net/HBEzc/3/

But I don't know how to port it to react. Hoping this will be considered. Thank you very much.

**Comment by Treora** [comment]
As reported in [issue 33](https://github.com/lovasoa/react-contenteditable/pull/33#issuecomment-242010980), you should be able to set this listener by passing it as the `onPaste` prop.
