### ISSUE TITLE
Demo page

### ISSUE THREAD

**Issue by WendellLiu** [lovasoa/react-contenteditable#32]
Maybe we need to build a simple demo page to make this project more attractive and more convenient for testing ?
:smile:

**Comment by lovasoa** [comment]
A pull request for this would have great chances of being accepted ;)

**Comment by george-g** [comment]
An usage example on jsbin: http://output.jsbin.com/zuvesamuzo

**Comment by lovasoa** [comment]
Done !  I finally created two demo pages on codesandbox.io : [a small demo](https://codesandbox.io/s/yqnkxx2qw1) and a [rich text editing demo with a lot of options](https://codesandbox.io/s/n067mmwjym).

**Comment by sanket-sangar** [comment]
how to limit number of characters ..?
