### ISSUE TITLE
Warning: Unknown prop `html` on <div> tag.

### ISSUE THREAD

**Issue by mewben** [lovasoa/react-contenteditable#34]
This may be related to https://fb.me/react-unknown-prop

This error shows. I'm using React v15.3.0

**Comment by WendellLiu** [comment]
I tried on React v15.3.1 but this warning didn't jump out.
The warning appeared If I modify the code to pass `html` to div.
```javascript
return React.createElement(
      this.props.tagName || 'div',
      {
        ...props,
        ref: (e) => this.htmlEl = e,
        onInput: this.emitChange,
        onBlur: this.props.onBlur || this.emitChange,
        onPaste: this.onPaste,
        contentEditable: !this.props.disabled,
        dangerouslySetInnerHTML: {__html: html},
        html // this line
      },
      this.props.children
    );
```
hope it's helpful

**Comment by lovasoa** [comment]
I'm not sure I understand... Of course, if you add `html` as a prop on a div, you get a warning. But why did you do that in the first place?

**Comment by WendellLiu** [comment]
@lovasoa
You are talking about my example code?
If so, this example code just show the only way I can get the same warning. On the other hand, I can't get the same warning on the normal case.

**Comment by lovasoa** [comment]
Yes, so there is no warning, no problem. Why did you open this issue?

**Comment by lovasoa** [comment]
Oooh, sorry, I just realized it's not you who opened the issue! Sorry.

**Comment by WendellLiu** [comment]
I just doubt that @mewben maybe did this mistake .

**Comment by lovasoa** [comment]
@mewben Do you see this warning with the latest react and latest react-contenteditable ?

**Comment by mewben** [comment]
Still getting the same error on a fresh install of `create-react-app`

node -v : v6.3.1
npm -v : 3.10.5
os: Mac

<img width="771" alt="screen shot 2016-08-26 at 11 23 26 pm" src="https://cloud.githubusercontent.com/assets/2163157/18010816/b99d89be-6be4-11e6-8e7d-817c147f34bd.png">

**Comment by lovasoa** [comment]
Oooh! I think I forgot to push the latest update to NPM!

**Comment by lovasoa** [comment]
[Done](https://www.npmjs.com/package/react-contenteditable)! Sorry!

**Comment by lovasoa** [comment]
Please confirm that I can now close this issue :)

**Comment by mewben** [comment]
Thanks. closing now.
