### ISSUE TITLE
Component should update on style change.

### ISSUE THREAD

**Issue by dammitjim** [lovasoa/react-contenteditable#38]
In response to the suggested change here: https://github.com/lovasoa/react-contenteditable/pull/36

Currently prop style changes are not rendered by the component.

I had a go at reflecting these changes for style but I believe it would require a deep equality comparison on the style prop passed in to understand that a render needs to occur.

You can see the changes I made as a temporary measure here: https://github.com/jimah/react-contenteditable/blob/master/src/react-contenteditable.js#L26

Lodash has a nice deep equal function but that would be adding a dependency.

**Comment by monolithed** [comment]
`className`, and other `attributes` should be supported as well.

**Comment by williamgranli** [comment]
@jimah @monolithed @ajbeaven is there any way to get this working without updating the lib? I'm thinking a quick fix in my component which uses this lib.

**Comment by ajbeaven** [comment]
Commenting on https://github.com/lovasoa/react-contenteditable/pull/59 might help get it merged quicker but yeah, if you have to use style (ie. can't use classes, that do trigger a render) then doing something like that makes sense. I'd suggest changing a class (even if it's not used for styling) instead of the key prop as there might be some performance gains you miss out doing the latter.

**Comment by shdwjk** [comment]
I tracked down a very annoying bug to this change.  I don't have a repro case for you, but here's what's going on:

### My component:
```
            <ContentEditable
              className={`${s.input} ${s.searchField}`}
              placeholder={'Search...'}
              html={props.query||''}
              onChange={props.onChange}
              {...props.theme(['input'])}
            />
```
`props.theme()` is a function that returns override styling as an object with a style property:
```
{
  style: { 
    input: {
      backgroundColor: '#ffffee'
    }
  }
}
```
(It doesn't actually matter, I can get the same behavior by just putting `style={{}}` in its place.)

### Behavior I'm seeing:
With any sort of `style=...` property, and redux providing the contents of `html`, typing in the input will always reset the cursor position to 0.  So typing `c` `a` `t` will yield in order `c` `ac` `tac`.  

Removing `style` from the `shouldComponentUpdate()` method (line `45` in my copy) removes this behavior.

Thoughts?
