### ISSUE TITLE
onFocus/onBlur

### ISSUE THREAD

**Issue by leefsmp** [lovasoa/react-contenteditable#41]
Is there an easy way to get onFocus and obBlur events fired by the component?

For example I don't want to respond to every onChange event when user is typing a long string, but only once the control is loosing focus...

Thanks!

**Comment by lovasoa** [comment]
All the properties you give to the component will be passed to the contenteditable div.
https://github.com/lovasoa/react-contenteditable/blob/master/src/react-contenteditable.js#L15
