### ISSUE TITLE
How to access the contentText instead of the innerHTML of the editable element ?

### ISSUE THREAD

**Issue by yanhaijing** [lovasoa/react-contenteditable#52]

**Comment by akinnee** [comment]
innerHTML is what I expected. Could you use `event.target.innerText`?

**Comment by akinnee** [comment]
One of the replies in this issue has a good example of a function that converts from innerHTML to contentText. https://github.com/lovasoa/react-contenteditable/issues/35

**Comment by yanhaijing** [comment]
thanks, other better way

**Comment by justinmc** [comment]
You can get ahold of the actual DOM element with `currentTarget`, so then you can do something like:

```
event.currentTarget.textContent
```
