### ISSUE TITLE
Deleting contenteditable="false" elements won't trigger onChange event.

### ISSUE THREAD

**Issue by TiagoOliveiraMarques** [lovasoa/react-contenteditable#56]
E.g.:
Lets say the ContentEditable component html is: "This is a <span contenteditable="false">Sample</span> text". If I put the cursor after the span and press the delete button, the whole span gets deleted but the onChange function won't be called with the updated value.

Am I missing something?

**Comment by lovasoa** [comment]
I cannot reproduce that. Can you provide an example code?
