### ISSUE TITLE
programmatically changing html prevents next onChange() from firing

### ISSUE THREAD

**Issue by leebailey88** [lovasoa/react-contenteditable#58]
It looks like the logic for determining when the onChange event should be fired needs to be updated.  When parent components programmatically update the html property, the `lastHtml` property is not updated.  `lastHtml` is only updated when users type and onChange events are fired.  `lastHtml` also needs to be updated on programmatic changes to the html; otherwise the component gets out of sync with its last state, and the next character changed in the component by the user will *not* fire the onChange event.

**Comment by lovasoa** [comment]
this should have been fixed in 2fadc9089299a79797642dbacdc5dcced561946d
