### ISSUE TITLE
Removing outline/border on focus

### ISSUE THREAD

**Issue by williamgranli** [lovasoa/react-contenteditable#65]
How do I remove the outline/border when the field is selected? Passing below object as prop (style) doesn't seem to work: 

```
{
  ':focus': {
      outline: 'none',
      border: 'none',
    },
}
```

Styling inline works fine otherwise, so I'm guessing that's how the lib is intended to be used. Sorry if I'm missing something.

Thanks!

**Comment by costagolub** [comment]
@williamgranli where do you specify the styles for the component? It looks like your code will not be working if you explicitly provide it through the props inside the component cause there a hurdle in React for this. You can add your styles in your stylesheet or add some react-css library to manage it.
Or you can omit` :focus` pseudo selector and use styles as the default state. Using this you will not have outline border.  
`<ContentEditable style={{outline: 'none'}} />`
