### ISSUE TITLE
pre-parse the src into javascript 

### ISSUE THREAD

**Issue by alihammad-gist** [lovasoa/react-contenteditable#7]
Please parse to javascript, not everyone is using es6.

**Comment by alihammad-gist** [comment]
sorry i was mistaken i just looked at the source inside node_modules, it isn't es6

**Comment by lovasoa** [comment]
Yes, it is es6 : https://github.com/lovasoa/react-contenteditable/blob/master/index.js

If you want to use an old version of the jsx parser that doesn't support es6, you'll also have to use the version of rect-contenteditable that predates es6: https://github.com/lovasoa/react-contenteditable/blob/d930b75508a99fcffa89212f5285803a20663088/index.js

**Comment by lovasoa** [comment]
It's just that I haven't updated the module on npm yet.

**Comment by drtz** [comment]
You can specify a transform in your package.json and dependent projects will run the transform automatically.
```
  "browserify": {
      "transform": ["babelify"]
  }
```

**Comment by tolmasky** [comment]
It would be a great help if you could add a pre-publish hook to turn it into non-react js, that way it would work with projects that use react without jsx out of the box for example.

It would be as easy as adding the following to your package.son:

```javascript
  "scripts": {
    "compile": "babel -d lib/ src/",
    "prepublish": "npm run compile"
  },
```

and putting your current code in src. This is detailed further here: http://mammal.io/articles/using-es6-today/ and is used by many popular libraries like react grid: https://github.com/STRML/react-grid-layout .

It would also help us as as it would make it work in tonicdev.com .

**Comment by lovasoa** [comment]
If you turn this into a pull request, I'd be glad to merge it!
