### ISSUE TITLE
在IE里报错 ，捉急，在线等

### ISSUE THREAD

**Issue by FISHAlready** [lovasoa/react-contenteditable#79]
ContentEditable.render():A valid React element(or null) must be returned. You may have returned undefined,an arry or some other invalid object.
以上是报错信息，我是这么写的：
<ContentEditable className="editor" ref="editor" html={this.state.html} onKeyUp ={this.editChange.bind(this)} />

**Comment by lovasoa** [comment]
I'm sorry, I do not understand Chinese.
