### ISSUE TITLE
Using styles makes cursor jump to the beginning 

### ISSUE THREAD

**Issue by DmitrySoshnikov** [lovasoa/react-contenteditable#81]
The code from the example in the README works, but if to add `style={{height: '400px'}}`, it starts to have the known issue with React and "contentEditable" -- cursors jumps to the beginning of the editing text. 

(I'm on Mac OS, Chrome)

**Comment by DmitrySoshnikov** [comment]
The solution I found is to create a needed wrapper with needed styles inside the content itself, rather than using React's `style` or `className` attributes.

**Comment by mvasin** [comment]
@DmitrySoshnikov How do you bypass html escaping? Do you create an extra inner React component?

**Comment by ajsantander** [comment]
In my case, the problem was solved when setting a css className to the ContentEditable component itself.

**Comment by bote795** [comment]
will try it, thx @ajsantander
