### ISSUE TITLE
Controllable ContentEditable

### ISSUE THREAD

**Issue by gregpmillr** [lovasoa/react-contenteditable#82]
I'm wondering if it's possible to make a ContentEditable controllable? I'm not exactly sure of how to get the name attribute of the ContentEditable itself so I can use it as a key for setState. This may be supported, but  I can't find much help on it.

Great project though! I'm simply using it as a vertical-expanding div for user input as I didn't want to use jQuery for this.

**Comment by lovasoa** [comment]
I'm not sure I understand what you mean. You can set any property you want on the element: just set them on your ContentEditable element, and they will be forwarded to the generated element.

see:
https://github.com/lovasoa/react-contenteditable/blob/master/src/react-contenteditable.js#L12-L22

**Comment by mmathys** [comment]
@gregpmillr see #84

**Comment by gregpmillr** [comment]
Ah thank you @mmathys. I haven't been able to come back to this but I agree with the referenced issue. I'll close this as I just had a misunderstanding of how to use the package with props. My fault.
