### ISSUE TITLE
Manipulating the HTML leaves the first character at the end when empty

### ISSUE THREAD

**Issue by nuthinking** [lovasoa/react-contenteditable#87]
I am trying to make a rich input text field with markup auto-assigned based on the content.

As initial test I tried to wrap whatever insert within a bold tag `<b>` after stripping down all the eventual markup. When the element is empty and I start typing, the first character insert stays at the end of the content. Demo here: https://codepen.io/nuthinking/pen/ZoKmRx?editors=1010

I really need this library to work, any idea what could be the issue?

Thanks a lot!

**Comment by lovasoa** [comment]
Every time you change the HTML programmatically,  the element is re-rendered, and the position of the caret is lost.

You have to be very careful about what you do in your handleChange function. The function you use:
```js
    handleChange: function(evt){
      const strippedText = evt.target.value.replace(/<[^>]*>/gi, '');
      this.setState({html: '<b>' + strippedText + '</b>'});
    }
```
is a bad idea.

I would advise making changes to the HTML contents only in the `onBlur` handler.
If you want to make live changes to the element being edited, you should use [`document.execCommand()`](https://developer.mozilla.org/en-US/docs/Web/API/Document/execCommand)

See the following example: https://codesandbox.io/s/n067mmwjym
