### ISSUE TITLE
Uncaught TypeError: Cannot read property 'replace' of undefined

### ISSUE THREAD

**Issue by aleemb** [lovasoa/react-contenteditable#88]
Fails in both cases, when string is `null` or when it is `undefined`.

![image](https://user-images.githubusercontent.com/46616/39673480-cf2ef732-5156-11e8-9577-a9d8e80702e4.png)

Should be `return str && str.replace...`.

Occurs in multiple places: https://github.com/lovasoa/react-contenteditable/commit/aa9a48732bef3352e9a958eea954a4d93b8315d7

**Comment by yodasodabob** [comment]
I'm having this problem too.

**Comment by eladonline** [comment]
i have this too

**Comment by yodasodabob** [comment]
If it helps, i manually put in the fix described by @aleemb into my app and it works fine now, no errors.

**Comment by davidcalhoun** [comment]
Also had this issue going from `2.0.7` to `2.1.0`.  Temporary lazy fix is to lock down the `package.json` version to `2.0.7`

**Comment by krue-doug** [comment]
There should really be a default set internally to an empty string.

**Comment by krue-doug** [comment]
@davidbarton where did you get 2.0.7? I don't see the tag here: https://github.com/lovasoa/react-contenteditable/tags

**Comment by davidbarton** [comment]
@krue-doug https://www.npmjs.com/package/react-contenteditable/v/2.0.7

**Comment by lovasoa** [comment]
Thank you very much to @aleemb for reporting and fixing this bug, and sorry for the lack of reactivity.

I published a new version on npm, so the bug is fixed as of [version `2.1.1`](https://www.npmjs.com/package/react-contenteditable/v/2.1.1).
