### ISSUE TITLE
Merge html value into event.currentTarget.value too

### ISSUE THREAD

**Issue by gausie** [lovasoa/react-contenteditable#93]
currentTarget is more accurate on many browsers

**Comment by lovasoa** [comment]
What do you mean by more accurate ? Are there cases where the event handler is attached to the wrong element in this library ?

**Comment by djvern** [comment]
`currentTarget` would be useful instead of `target` in my use case as using flow causes an error which is only solved by using `currentTarget`: https://github.com/facebook/flow/issues/2099
