### ISSUE TITLE
Set focus?

### ISSUE THREAD

**Issue by MitchEff** [lovasoa/react-contenteditable#95]
Is there a way of setting focus on the div? It doesn't seem to pass up a ref or anything.

**Comment by MitchEff** [comment]
Wait! Sorry, never mind - I just saw the 'htmlEl' property.

**Comment by pedro-mass** [comment]
This is old, but has anyone gotten this to work with `innerRef`?
Calling `.focus()` doesn't seem to add the cursor to it, or trigger the `onFocus` prop.

Followed this doc on setting the ref: https://codepulse.blog/how-to-focus-element-in-react/
