### ISSUE TITLE
How to save the text as plain text 

### ISSUE THREAD

**Issue by ramisalem** [lovasoa/react-contenteditable#97]
Hi
my app is to let the user type content in the Content Editable and then I send the text they entered to a redux store my problem is that when I send it to the store it looks like this 

"user typed this line og&nbsp; &nbsp; &nbsp;" 

it happens when the user pressed white space   
here is my code 

> class Editor  extends Component {
  constructor(props) {
    super(props);
    this.state = { html: "" }
    this.handleChange = this.handleChange.bind(this);
  }

  handleChange(event) {
    this.setState({
      html: event.target.value 
    });
     this.props.onChangeText(this.state.html);
     this.props.onSpellCheck(this.state.html);
     
  }

> render() {
        let correctionsWords = this.props.correctionsList ? this.props.correctionsList : [] ;
         console.log('befor mapping ' , correctionsWords) // {'word': [1,3,4]}
        let correctionList =  Object.keys(correctionsWords).map(  (key)  => {
            return (
              <div key={key}>
                  {
                      
                       <ul>
                         <li> key: {key} { /* word  */}
                          <ul> 
                                  {correctionsWords[key].map(el => (
                                    <li key={el}>{el}</li>
                                  ))}

                          </ul>
                         </li>  
                         </ul>
                  } 
              </div> 
            ); });

     return (
    <div className="cont">  
      <ContentEditable
        className="editable"
        html={this.state.html} // innerHTML of the editable div
        disabled={false} // use true to disable edition
        onChange={this.handleChange} // handle innerHTML change
        placeholder="Type something..."
        
      />
       <div className="wrong-words">
             {correctionList}   
        </div>    
    </div>
    );
  }
}

const mapStateToProps = state => {
    return {
        text: state.edi.text ,
        wrongWords: state.edi.errorWordslist,
        correctionsList: state.edi.correctionsList 
        
    };
};

const mapDispatchToProps = dispatch => {
  return {
      onStart: () => dispatch(actionCreators.start()),
      onChangeText: (value)   => dispatch(actionCreators.TextChange(value)),
      onSpellCheck: (word)    => dispatch(actionCreators.ErorrWordsList(word)),
      
  }
};

How can I solve this problem ?

**Comment by lovasoa** [comment]
This is out of the scope of this library. You can use an external library like https://www.npmjs.com/package/html2plaintext or simple extract the `textContent` of the underlying DOM element.

**Comment by ramisalem** [comment]
@lovasoa  thanks

**Comment by sanbornhilland** [comment]
> This is out of the scope of this library. You can use an external library like [npmjs.com/package/html2plaintext](https://www.npmjs.com/package/html2plaintext) or simple extract the `textContent` of the underlying DOM element.

I ended up here after having the same issue and being a bit confused. I just want to clarify this for any future visitors with the same issue. [textContent](https://developer.mozilla.org/en-US/docs/Web/API/Node/textContent) is a property on the DOM node that does not parse the Node value as HTML so is possible what you are looking for if you are looking for the plain text contents of the Node.

Example:

```
onChange({ nativeEvent }) {
  this.setState({
    value: nativeEvent.target.textContent,
  })
}
```
